spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-logs}:${DB_PORT:5432}/${DB_NAME:bd_logs}?ssl=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  notification-service:
    ws-url: ${NOTIFICATION_SERVICE_WS_URL:ws://notification-service:8085/ws/internal/notificaciones/logs}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:directory}:8761/eureka/
  instance:
    prefer-ip-address: true
