spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_logs
    username: postgres
    password: root

app:
  notification-service:
    ws-url: ws://localhost:8085/ws/internal/notificaciones/logs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    "[com.metradingplat.log_service]": DEBUG
